[package]
name = "ci-battery-pack-test"
version = "0.1.1"
edition = "2021"
rust-version = "1.91.1"
description = "CI battery pack test"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jlizen/ci-battery-pack-test"


[workspace]
members = [".", "xtask"]



[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "example_bench"
harness = false



[[bin]]
name = "ci-battery-pack-test"
path = "src/main.rs"


[package.metadata.battery-pack]
ci-battery-pack = { features = ["benchmarks"] }
